version: "3.3"
services:
  php-composer:
    build:
      context: ./docker/composer
    image: composer:latest
    volumes:
      - .:/var/www

  nginx:
    build:
      context: ./docker/nginx
    image: nginx-php:latest
    ports:
      - 80:80
